// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3sVPNcMK_72ToEmerHLEYQevGZx7XuJE',
    appId: '1:66676220696:web:04134d4824a9a240a4746d',
    messagingSenderId: '66676220696',
    projectId: 'first-project-30ec1',
    authDomain: 'first-project-30ec1.firebaseapp.com',
    storageBucket: 'first-project-30ec1.appspot.com',
    measurementId: 'G-CJ9MSH658R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXSlLLgVnGcjvt3c7w4sFnBEpP0quLHxU',
    appId: '1:66676220696:android:4b2b339858ce5141a4746d',
    messagingSenderId: '66676220696',
    projectId: 'first-project-30ec1',
    storageBucket: 'first-project-30ec1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDziZK5RwPjT6_zON8P4qB-y0nRNTSElVo',
    appId: '1:66676220696:ios:d5c6e3352d483a28a4746d',
    messagingSenderId: '66676220696',
    projectId: 'first-project-30ec1',
    storageBucket: 'first-project-30ec1.appspot.com',
    iosBundleId: 'com.example.tranning2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDziZK5RwPjT6_zON8P4qB-y0nRNTSElVo',
    appId: '1:66676220696:ios:d5c6e3352d483a28a4746d',
    messagingSenderId: '66676220696',
    projectId: 'first-project-30ec1',
    storageBucket: 'first-project-30ec1.appspot.com',
    iosBundleId: 'com.example.tranning2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3sVPNcMK_72ToEmerHLEYQevGZx7XuJE',
    appId: '1:66676220696:web:bfd966d399747d82a4746d',
    messagingSenderId: '66676220696',
    projectId: 'first-project-30ec1',
    authDomain: 'first-project-30ec1.firebaseapp.com',
    storageBucket: 'first-project-30ec1.appspot.com',
    measurementId: 'G-KXC97V9XYQ',
  );
}
